wallpaper {
    monitor = DP-3
    path = /home/MageOfLuck/Pictures/Ariandel.jpg
    #fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/MageOfLuck/Pictures/Merlin1920-1080.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/MageOfLuck/Pictures/sekiro.jpg
    fit_mode = cover
}

splash = false